### ISSUE TITLE
About how to download Tobacco3482  and   theSmallTobacco_nums.csv file is missing from the project

### ISSUE THREAD

**Issue by wufj** [javiferran/document-classification#2]
Hello, I think your paper is very interesting, I want to reproduce your code, but encountered some problems, Tobacco3482 can not be downloaded, SmallTobacco_nums.csv is missing, can you tell me how to solve these problems, thank you very much

**Comment by javiferran** [comment]
Hi, Thanks!

Tobacco3482 link has been removed. Now it can be downloaded [here](https://www.kaggle.com/patrickaudriaz/tobacco3482jpg). Regarding SmallTobacco_nums.csv, it is just SmallTobacco.csv but without the last column, which is generated when creating the .txt files with OCR.

**Comment by wufj** [comment]
Thank you for your help, I used ST_hdf5_dataset_creation.py to generate a hdf5 file, but there are ten hdf5 in eff_small_train.py.

**Comment by javiferran** [comment]
You can create as many different shuffled versions of Small Tobacco as you want by rerunning ST_hdf5_dataset_creation.py.

**Comment by wufj** [comment]
Thank you very much, I seem to get it！

**Comment by wufj** [comment]
Hello, excuse you, I use distr_effnet_shear.py for training, the accuracy is 0.06, which makes me very confused, can you tell me what I did wrong
